### ISSUE TITLE
Problem authenticating

### ISSUE THREAD

**Issue by karline** [gupta-ankit/fitgem_oauth2#1]
Hi, thanks for your hard work!

I can't seem to get this to authenticate with Fitbit, either while using localhost or a remote host:

Fitbit
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Developer information: invalid_request - Invalid redirect_uri parameter value

Any thoughts? I have triple checked that the redirect_uri matches the value on Fitbit's dev site.

**Comment by gupta-ankit** [comment]
It works for me.

In case, you need to test it with a rails application, here is an example https://github.com/gupta-ankit/FitgemOAuth2Rails
