### ISSUE TITLE
Valid 201 responses are being handled as errors

### ISSUE THREAD

**Issue by JohnnyCon** [gupta-ankit/fitgem_oauth2#11]
There are certain operations, like creating a subscription (which is supported by this gem) that return a 201 (for created).  However, the library is catching that status and raising it as an exception "unexpected http response".  Seems like an easy fix.  Can submit a PR if needed. 

Thanks

**Comment by mkpdev** [comment]
Valid 204 responses are also handled as errors

**Comment by gupta-ankit** [comment]
thanks for pointing that out. I will fix in a few days.

**Comment by gupta-ankit** [comment]
https://github.com/gupta-ankit/fitgem_oauth2/commit/f75cd1b257ff5dbde848b77e1d6647a5464d85d1 fixes this issue
