### ISSUE TITLE
Fix your gemspec

### ISSUE THREAD

**Issue by zenspider** [gupta-ankit/fitgem_oauth2#16]
Don't make it hard to find this repo. Please fill out your gemspec properly. Also include the README and other artifacts in the gem so things are more discoverable.

**Comment by gupta-ankit** [comment]
Thank you for your feedback and the pull request. I will work on the Readme. I am not sure what I can change in the `gemspec`

Also, it seems to not have any conflicts when I run rspec on my machine.
