### ISSUE TITLE
initial authorization

### ISSUE THREAD

**Issue by cecat** [gupta-ankit/fitgem_oauth2#18]
Hi,
I'm trying to learn (from scratch) Ruby and Oauth2 simultaneously as I'd like to have a fitbit widget in a smashing dashboard.  When I first grabbed the [fitbit widget](https://github.com/kevintuhumury/dashing-fitbit) I was (and still am) not sure what to specify for the (required) callback URL, but in any case I got authorization decline errors running the provided bootstrap code fitbit_authorizer.rb.  I found fitgem_oauth2 through the comments about the need to move to Oauth2, but I am not sure how to recreate fitbit_authorizer.rb using fitgem_oauth2.  Has anyone created an updated version of the fitbit widget, or can you suggest how to modify the old fitbit_authorizer.fb to work with Oauth2?
Thanks for any advice or help-
CeC

**Comment by gupta-ankit** [comment]
Hi @cecat, Sorry for late reply. With OAuth2, the authorization should happen separately. When you authorize an application with Fitbit API and `omniauth` gem, you will receive a token which you can use with the `fitgem_oauth2` gem.

Here is an example of how to use the gem in a rails application https://github.com/gupta-ankit/FitgemOAuth2Rails

**Comment by cecat** [comment]
﻿Thanks!
