### ISSUE TITLE
Problem with array responses

### ISSUE THREAD

**Issue by randomizor** [gupta-ankit/fitgem_oauth2#4]
Calling the devices method is returning:

`undefined method merge! for #<Array>`

Due to merging the headers_to_keep in parse_response

**Comment by randomizor** [comment]
Thanks for your work on this by the way, currently have clients breathing down my neck about making the switch over so don't have time to wait for the Fitgem maintainers (who have done an excellent job thus far) to catch up.

**Comment by gupta-ankit** [comment]
Thanks for reporting the bug.

I have made some change to the output for API calls that return an array.

The output from the API call will be an object that will contain the array as a value to key ["body"]

With this change, the output for devices call will look like following

(this is the json output, when calling the method #devices, you will receive a Hash instead)
{
'body' : [
    {
      "battery": "...",
      "deviceVersion": "...",
      "features": [],
      "id": "...",
      "lastSyncTime": "...",
      "mac": "...",
      "type": "..."
    }
  ],
  "fitbit-rate-limit-limit": "150",
  "fitbit-rate-limit-remaining": "140",
  "fitbit-rate-limit-reset": "1774"
}

This fix affects 1.0.4 and later. Let me know how it goes.
