### ISSUE TITLE
Getting "FitgemOauth2::UnauthorizedError" when trying to get data

### ISSUE THREAD

**Issue by Eblohm** [gupta-ankit/fitgem_oauth2#6]
Hi,

I'm currently in the process of switching my project over to Oauth2 gems to authenticate and get data from Fitbit, users can sign in and sign up successfully using the 'omniauth-fitbit' gem, however when I try to access the data I'm getting the `FitgemOauth2::UnauthorizedError`. 

I'm using the same client id and client secret that the omniauth-fitbit gem is using so I know they work, and getting activity data is within the scope of my request when authenticating the user.

Any idea what I might be doing that's causing this issue?

Thanks,
-Eric

**Comment by Eblohm** [comment]
Figured it out, wasn't using the correct access token to get the data.

**Comment by zapbuild007** [comment]
Hello,

What is correct access token? I am facing same error, I am aslo switching to Oauth2 gems, I have also set scope of my request
My token is looking like this "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2ZpdHRvZ2V0aGVyemFwLmF1dGgwLmNvbS8iLCJzdWIiOiJmaXRiaXR8M0IzNVpOIiwiYXVkIjoiVVNaNzhvUnp3SUZ4N2U0Z09qcnBZQTFWWklEQlpvOHUiLCJleHAiOjI0NzMxMzk4NjIsImlhdCI6MTQ3MzEzOTg2Mn0.EbEHdRyurFJ_0mnbm5boM7J8QZl-q5Ro5dIQbV7PI4A"

Thanks,
-Sandeep

**Comment by Eblohm** [comment]
When a user is successfully authenticated through Fitbit, it returns 2 tokens (these are unique to each user), an access token, and a refresh token. The access token is the one that allows the user to sign in through Fitbit, and is the one that needs to be refreshed. In order to refresh the access token, you have to use the refresh token. 

So when you're using this gem, when you call the `refresh_access_token` method, instead of sending the access token, send the refresh token, so something like 

`
new_access_token = refresh_access_token(refresh_token)
user.access_token = new_access_token['access_token']
user.refresh_token = new_access_token['refresh_token']
user.save
`

The variable names can be changed, obviously, but the ['access_token'] and ['refresh_token'] cannot, because those are the names that Fitbit gives and they cannot be changed on our end.

Hope this helps!
