### ISSUE TITLE
Getting User Scopes

### ISSUE THREAD

**Issue by admande** [gupta-ankit/fitgem_oauth2#7]
Is there a means to return the scopes the user has selected or preventing errors from arising if a user has not selected certain scopes?

**Comment by gupta-ankit** [comment]
The Fitbit API does not have an endpoint for scopes. 

Currently, fitgem_oauth2 should raise an error if you request something that is not in scope. However, I have not tested it. Can you confirm if it is raising an error and what kind?

That said, I think I might add a more descriptive error for out-of-scope requests, in a near future release.

**Comment by admande** [comment]
Yes, that's the error that's getting raised. So do you recommend that I "rescue" every attempt to get something that wasn't approved by the user?

**Comment by gupta-ankit** [comment]
Unfortunately, yes! Until, Fitbit API provides a way to access permitted scopes in its API

An alternative would be to store the scopes that the user granted permission for and check if you have permission before accessing a resources from the scope.

When the user grants the permission to access his/her data Fitbit redirects to the redirect_uri and accepted scopes are part of the URL (as I understand from the documentation)
[See Redirect URIs](https://dev.fitbit.com/docs/oauth2/)

**Comment by admande** [comment]
The redirect URL includes the grant type and code but not the scope as far as I can tell.. Do you know where to rescue if someone unclicks the profile or clicks "deny"?

**Comment by gupta-ankit** [comment]
Whatever I say below is from memory and I have not tested it. However, as I recall from reading somewhere:

The redirect URI will include scopes if it is implicit grant. In case of explicit grant, the granted scopes are part of the POST parameters when the Fitbit server returns the code (the code is what your app exchanges with Fitbit server for an access token and refresh token). Now, in my existing applications, I am using Omniauth, which as far as I can tell, handles the receiving and exchange of code internally and does not give me access to anything but the access and refresh token. I am currently working on a way to figure out if it is even possible. In the meantime, I will just use `rescue`

**Do you know where to rescue if someone unclicks the profile or clicks "deny"?**

This depends on what you are using to implement OAuth. OAuth authentication is not part of `fitgem_oauth2` and therefore this should be taken care of when the user registers/tries to login via Fitbit. You can use the sample fitgem_oauth2 Rails application (details in readme) to test out the different scenarios before implementing them in your business logic.

**Comment by admande** [comment]
Thanks for all your help. I really appreciate it 👍
