### ISSUE TITLE
Refreshing tokens?

### ISSUE THREAD

**Issue by Eblohm** [gupta-ankit/fitgem_oauth2#8]
I can't seem to figure out how to handle if the users access_token has expired, currently the only way around it I can figure out is to force the user to log out after an hour (when the token expires) and have them log in again. Is it possible to refresh the access_token with this gem?

**Comment by albertpak** [comment]
@Eblohm what did you end up using? what was your solution?

**Comment by Eblohm** [comment]
@albertpak The access token expires an hour after it's created/refreshed, so when the user signs up I stored the current time + 1 hour, and then whenever the user data refreshes I checked if the current time was later than the saved time, and if it was, I'd call the 
`refresh_access_token(refresh_token)` function from this gem, and then store the new access token, refresh token, and time + 1 hour to the user table.

Hope that helps!

**Comment by kmanzana** [comment]
It is simpler to just refresh the token whenever the response for an api request was that the token had expired.

```
{
    "errors": [
        {
            "errorType": "expired_token",
            "message": "Access token expired: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0MzAzNDM3MzUsInNjb3BlcyI6Indwcm8gd2xvYyB3bnV0IHdzbGUgd3NldCB3aHIgd3dlaSB3YWN0IHdzb2MiLCJzdWIiOiJBQkNERUYiLCJhdWQiOiJJSktMTU4iLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE0MzAzNDAxMzV9.z0VHrIEzjsBnjiNMBey6wtu26yHTnSWz_qlqoEpUlpc"
        }
    ]
}
```
