### ISSUE TITLE
Verifying a subscriber?

### ISSUE THREAD

**Issue by Eblohm** [gupta-ankit/fitgem_oauth2#9]
How do I go about verifying a subscriber with this gem? I see the subscriber methods but none of them allow me to get through the verification of a subscriber phase when I create one on my app on Fitbits website.

**Comment by gupta-ankit** [comment]
Verification is not part of the fitgem_oauth2 API as it is a one-time operation and more importantly dependent on how the application is implemented (RoR or something else). In addition the verification is not a user-level call. It is an application-specific call.

However, if you have a Ruby on Rails application, here is a controller and action you can use for verification. 

```
class SubscriptionsController < ApplicationController
  protect_from_forgery :except => [:index]

  require 'json'

  def index
    verification_code = 'your_verification_code'
    if params[:verify]
      if params[:verify] == verification_code
        render :nothing => true, :status => 204
      else
        render :nothing => true, :status => 404
      end
  end
end

```

**Comment by Eblohm** [comment]
Ah, that makes sense. Thanks for the code, too. I was able to successfully verify the subscription. I'm also able to create a subscription for users, but what do I do from here? How do I actually read the notification Fitbit sends me? I know it won't have the updated data, but it'll contain the user data and for what day, so I can then send a request to them. I can't figure out how to properly read the notification that Fitbit sends me. Is there a method in this gem for that?

**Comment by gupta-ankit** [comment]
Glad to help! :)

Once the subscriber is verified and you add a subscription, Fitbit will periodically POST a json request. Parse the request to see the what resource, date and user needs to be updated.

here is the relevant [documentation](https://dev.fitbit.com/docs/subscriptions/#receiving-update-notifications)
